language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source;
  
script: phpunit --configuration module/Category/tests/phpunit.xml --coverage-clover=coverage.clover
        
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
