<ol class="breadcrumb">
    <li>
        <a href="<?php echo $this->url('download'); ?>">
            <span class="glyphicon glyphicon-home"></span>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url('download', array('subject' => $subject->abbreviation)); ?>">
            <?php echo $this->escapeHtml($subject->abbreviation); ?>
        </a>
    </li>
    <li class="active"><?= $category->name ?></li>
    <a href="<?php echo $this->url('upload') ?>" class="pull-right hidden-xs" style="text-decoration: none;"><span class="glyphicon glyphicon-upload"></span> <small>Upload</small></a>
</ol>

<ul class="nav nav-pills nav-stacked">
    <?php foreach ($files as $file) : ?>  
    <li>
        <a href="<?= $this->url('download', array('subject' => $subject->abbreviation, 'category' => $category->name, 'file' => $file->id)) ?>" class="list-group-item shorten-long-text"> 
            <span class="glyphicon glyphicon-file"></span>
            <?php echo $this->escapeHtml($file->name); ?>
            <span class="badge hidden-xs"><?php echo $this->escapeHtml($file->downloadCount); ?></span>   
        </a>
    </li>
    <?php endforeach; ?>
</ul>